// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7uW8YeK8hGImyjgpeZA6zGAWEm8u8yxM',
    appId: '1:509172806109:web:662cac86ef0b55cd128634',
    messagingSenderId: '509172806109',
    projectId: 'healthbridge-b5bb1',
    authDomain: 'healthbridge-b5bb1.firebaseapp.com',
    storageBucket: 'healthbridge-b5bb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCsz9O8REdIEZOYP5eO99p3Po5sNANyA',
    appId: '1:509172806109:android:626d8dc107c05a1a128634',
    messagingSenderId: '509172806109',
    projectId: 'healthbridge-b5bb1',
    storageBucket: 'healthbridge-b5bb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCzGhvTijoYMPHAXULAK8OK473V7af-I',
    appId: '1:509172806109:ios:2bde3d57ceff0134128634',
    messagingSenderId: '509172806109',
    projectId: 'healthbridge-b5bb1',
    storageBucket: 'healthbridge-b5bb1.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7uW8YeK8hGImyjgpeZA6zGAWEm8u8yxM',
    appId: '1:509172806109:web:8924ed670f065609128634',
    messagingSenderId: '509172806109',
    projectId: 'healthbridge-b5bb1',
    authDomain: 'healthbridge-b5bb1.firebaseapp.com',
    storageBucket: 'healthbridge-b5bb1.firebasestorage.app',
  );
}
